name: birthday_reminder

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 01:00 執行（台灣時間 09:00）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run birthday reminder
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          BIRTHDAY_JSON: ${{ secrets.BIRTHDAY_JSON }}
        run: python birthday_cron.py
